---
- name : install-default-jdk and maven and git
  hosts: builder 
  become: yes

  tasks:
  - name: Ensure that default-jdk and maven and git package is present
    apt:
     name: default-jdk maven git
     state: present

- name : install-default-jdk-prod  and tomcat9
  hosts: prod 
  become: yes

  tasks:
  - name: Ensure that default-jdk and tomcat9 package is present in pod
    apt:
     name: default-jdk tomcat9
     state: present

- name : change-work-dir-in-builder
  hosts: builder 
  become: yes

  tasks: 
  - name: Ensure that work dir is present in builder
    shell: 
      args:
        chdir: /home/

- name : get-git-repository 
  hosts: builder 
  become: yes

  tasks: 
  - name: Ensure  that  install git project
    git: 
      repo: 'https://github.com/tarekkhoury/mywebapplication.git'
      dest: /home
