---
- name : install-default-jdk
  hosts: builder 
  become: yes

  tasks:
  - name: Ensure that default-jdk package is present
    apt:
     name: default-jdk
     state: present

- name : install-maven
  hosts: builder 
  become: yes

  tasks:
  - name: Ensure that maven package is present
    apt:
     name: maven
     state: present

- name : install-git
  hosts:  
  become: yes

  tasks:
  - name: Ensure that git package is present
    apt:
     name: git
     state: present
     