
- name : install-default-jdk and maven and git
  hosts: builder
  become: yes

  tasks:
  - name: Ensure that default-jdk and maven and git package is present
    apt:
      pkg:
        - default-jdk
        - maven
        - git

- name : install-default-jdk-prod  and tomcat9
  hosts: prod
  become: yes

  tasks:
  - name: Ensure that default-jdk and tomcat9 package is present in pod
    apt:
      pkg:
        - default-jdk
        - tomcat9

- name : prepare project directory for work 
  hosts: builder
  become: yes

  tasks:
  - name:  remove folder mywebapplication 
    file:
      path: /home/mywebapplication
      state: absent

- name : get-git-repository
  hosts: builder
  become: yes

  tasks:
  - name: Ensure  that  install git project
    git:
      repo: 'https://github.com/tarekkhoury/mywebapplication.git'
      dest: /home/mywebapplication