- name : install-default-jdk and maven and git
  hosts: builder
  become: yes

  tasks:
  - name: Ensure that default-jdk and maven and git package is present
    apt:
      pkg:
        - default-jdk
        - maven
        - git

- name : install-default-jdk-prod  and tomcat9
  hosts: prod
  become: yes

  tasks:
  - name: Ensure that default-jdk and tomcat9 package is present in pod
    apt:
      pkg:
        - default-jdk
        - tomcat9

- name : change-work-dir-in-builder
  hosts: builder
  become: yes



  tasks:
  - name: Ensure that work dir is present in builder
    file:
      path: /home/mywebapplication
      state: absent
      #    shell:
      # cmd: mkdir /home/mywebapplication

- name : get-git-repository
  hosts: builder
  become: yes

  tasks:
  - name: Ensure  that  install git project
    git:
      repo: 'https://github.com/tarekkhoury/mywebapplication.git'
      dest: /home/mywebapplication


- name : make  war file
  hosts: builder
  become: yes

  tasks:
  - name: make war
    shell:
      cmd:  mvn -f /home/mywebapplication/pom.xml clean package